layout_spectrum: 0.5775532543193549
description: ''
name: 'diving,travel&photography'
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
navigation:
  - id: 27fded67-ae5a-4d5c-9a25-3084a95f32b6
    name: Lotus Barge
    type: content
typography_spectrum: 0.7259697
color:
  brandStrength: 0.3697604157496244
  saturation: 0.4383062953129411
  brandColors:
    - '#E1E6FA'
    - '#C4D7ED'
    - '#ABC8E2'
    - '#375D81'
    - '#183152'
  lightness: 0.8831145593430847
  rhythmicContrast: 0.6739813643507659
